include src/config.mk

.PHONY: all cgis clean clis distclean distrib docs includes guis libs tests

all: ;
	./configure.sh
	make -isC ./src all

cgis: ;
	make -isC ./src cgis

clean: ;
	make -isC ./src clean

distclean: ;
	make -isC ./src distclean

distrib: ;
	make -isC ./src distrib

docs: ;
	make -isC ./src docs

includes: ;
	make -isC ./src includes

guis: ;
	make -isC ./src guis

libs: ;
	make -isC ./src libs

tests: ;
	make -isC ./src tests
