# Copyright: Kaiserrundfunk.com / Jonacast 2019

# ./src/config.mk 23.05.2019 12:05:49

# Created by Configure at compiling - do not edit this file


# Globals:

TSC_NAME=vipclub-0.1.1-1
TSC_Major=0
TSC_Minor=0
TSC_Release=1
TSC_Patch=1
TSC_Echo=/usr/bin/echo
TSC_Echoe=/usr/bin/echo -e
TSC_MK=/usr/bin/make
