// Copyright: Kaiserrundfunk.com / Jonacast 2019

// ./src/config.h 23.05.2019 10:08:11

// Created by Configure at compiling - do not edit this file


// Globals:

#define TSC_NAME vipclub-0.1.1-1
#define TSC_Major 0
#define TSC_Minor 0
#define TSC_Release 1
#define TSC_Patch 1
#define TSC_Echo /usr/bin/echo
#define TSC_Echoe /usr/bin/echo -e
#define TSC_MK /usr/bin/make
