// Copyright: Kaiserrundfunk.com / Jonacast 2019

// ./src/config.h 23.05.2019 13:11:50

// Created by Configure at compiling - do not edit this file


// Globals:

#define TSC_NAME vipclub-0.1.1-1
#define TSC_Major 0
#define TSC_Minor 0
#define TSC_Release 1
#define TSC_Patch 1
#define TSC_Echo /usr/bin/echo
#define TSC_Echoe /usr/bin/echo -e
#define TSC_MK /usr/bin/make
#define CC /usr/bin/gcc
#define CFLAGS -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -D_REENTRANT
#define GLIBFLAGS -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
#define GTKFLAGS -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl
