# Copyright: Kaiserrundfunk.com / Jonacast 2019

# ./src/config.mk 14.02.2020 00:43:37

# Created by Configure at compiling - do not edit this file


# Globals:

TSC_NAME=vipclub-0.1.1-1
TSC_Major=0
TSC_Minor=0
TSC_Release=1
TSC_Patch=1
TSC_Echo=/usr/bin/echo
TSC_Echoe=/usr/bin/echo -e
TSC_MK=/usr/bin/make
CC=/usr/bin/gcc
AR=
RANLIB=
CFLAGS=-I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/uuid -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -I/usr/include/wayland -I/usr/include/libxkbcommon -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -pthread
GLIBFLAGS=-I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include
GTKFLAGS=-lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0
TSC_Libs=-L /develop/git/VipClub/develop/../lib
TSC_Incl=-I /develop/git/VipClub/develop/../incl
