// Copyright: Kaiserrundfunk.com / Jonacast 2019

// ./src/config.h 14.02.2020 02:00:29

// Created by Configure at compiling - do not edit this file


// Globals:

#define TSC_NAME vipclub-0.1.1-1
#define TSC_Major 0
#define TSC_Minor 0
#define TSC_Release 1
#define TSC_Patch 1
#define TSC_Echo /usr/bin/echo
#define TSC_Echoe /usr/bin/echo -e
#define TSC_MK /usr/bin/make
#define TSC_CC /usr/bin/gcc
#define TSC_CP /usr/bin/cp
#define TSC_RM /usr/bin/rm -f
#define TSC_RD rd
#define TSC_AR /usr/bin/ar -rs
#define CFLAGS -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/uuid -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -I/usr/include/wayland -I/usr/include/libxkbcommon -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -pthread
#define GLIBFLAGS -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include
#define GTKFLAGS -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0
#define TSC_Libs /develop/git/VipClub/develop/lib
#define TSC_Incl /develop/git/VipClub/develop/inc
